# Docker Registry Cleaner Configuration
# This file contains shared configuration for all scripts

# Registry Configuration
registry:
  url: "docker-registry:5000"
  repository: "dominodatalab"

# Kubernetes Configuration
kubernetes:
  platform_namespace: "domino-platform"
  compute_namespace: "domino-compute"
  pod_prefixes: ["model-", "run-"]

# Mongo Configuration
mongo:
  host: "mongodb-replicaset"
  port: 27017
  replicaset: "rs0"
  db: "domino"
  collection: "environment_revisions"

# Analysis Configuration
analysis:
  max_workers: 4
  timeout: 300
  output_dir: "../reports"

# Default Report Paths
reports:
  deletion_analysis: "deletion-analysis.json"
  filtered_layers: "filtered-layers.json"
  image_analysis: "final-report.json"
  images_report: "images-report"
  layers_and_sizes: "layers-and-sizes.json"
  tags_per_layer: "tags-per-layer.json"
  tag_sums: "tag-sums.json"
  workload_report: "workload-report.json"

# Security Configuration
security:
  dry_run_by_default: true
  require_confirmation: true 