apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: skopeo
    docker-registry-client: "true"
  name: skopeo
  namespace: domino-platform
spec:
  containers:
  - image: quay.io/skopeo/stable:latest
    name: skopeo
    command: ["sleep"]
    args: ["3600"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
