apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-registry-cleaner
  namespace: domino-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: docker-registry-cleaner
  namespace: domino-platform
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "patch"]
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: docker-registry-cleaner
  namespace: domino-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: docker-registry-cleaner
subjects:
  - kind: ServiceAccount
    name: docker-registry-cleaner
    namespace: domino-platform