{{- if and .Values.frontend.enabled .Values.frontend.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "docker-registry-cleaner.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "docker-registry-cleaner.name" . }}-frontend
    helm.sh/chart: {{ include "docker-registry-cleaner.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: frontend
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "docker-registry-cleaner.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          {{ .Values.frontend.networkPolicy.ingressNamespaceLabel | toYaml | trim }}
      {{- with .Values.frontend.networkPolicy.ingressPodLabels }}
      podSelector:
        matchLabels:
          {{ . | toYaml | trim }}
      {{- end }}
    ports:
    - port: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
{{- end }}
